export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',

  GATEWAY: {
    PRIVATE: 'GATEWAY_PRIVATE_KEY_PATH',
    PUBLIC: 'GATEWAY_PUBLIC_KEY_PATH',
  },

  BACKEND: 'BACKEND_URL',
  FRONTEND: 'FRONTEND_URL',
  DATABASE: 'DATABASE_URL',
  RABBITMQ: 'RABBITMQ_URL',

  HTTP: {
    PORT: 'HTTP_PORT',
    HOST: 'HTTP_HOST',
    CORS: 'HTTP_CORS',
  },

  REDIS: {
    USER: 'REDIS_USER',
    PASSWORD: 'REDIS_PASSWORD',
    HOST: 'REDIS_HOST',
    PORT: 'REDIS_PORT',
  },

  BETTER_AUTH: {
    SECRET: 'BETTER_AUTH_SECRET',
    URL: 'BETTER_AUTH_URL',
  },

  GOOGLE: {
    ID: 'GOOGLE_CLIENT_ID',
    SECRET: 'GOOGLE_CLIENT_SECRET',
  },

  TWILIO: {
    ACCOUNT_SID: 'TWILIO_ACCOUNT_SID',
    SERVICE_SID: 'TWILIO_SERVICE_SID',
    AUTH_TOKEN: 'TWILIO_AUTH_TOKEN',
    PHONE_NUMBER: 'TWILIO_PHONE_NUMBER',
  },

  SERVICES: {
    AUTH: 'AUTH_SERVICE_URL',
  },

  RESEND: {
    API_KEY: 'RESEND_API_KEY',
    MAIL_FROM: 'RESEND_MAIL_FROM',
  },
} as const;
