export const STATUSES = {
  OK: 'OK',
  ERROR: 'ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  SOCIAL_REGISTRATION_NOT_ALLOWED: 'SOCIAL_REGISTRATION_NOT_ALLOWED',
} as const;
